# Generated by Django 3.0 on 2019-12-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('fullname', models.CharField(max_length=256)),
                ('position', models.CharField(max_length=256)),
            ],
        ),
    ]
